version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: jerk-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    links:
      - db
    volumes:
      - ./:/var/www:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: jerk-webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "4488:80"
      - "4434:433"
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: jerk-db
    restart: unless-stopped
    tty: true
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: jerk
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: jerkuser
      MYSQL_PASSWORD: jerkpassword
      SERVICE_NAME: jerk-mysql
    volumes:
      - dbdata:/var/lib/mysql/:delegated
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/www/data:delegated
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
